version: 1.0.{build}
image: Previous Visual Studio 2017
configuration: Release
clone_depth: 1
clone_folder: c:\MP\
init:
- cmd: 
cache: packages
build_script:
- cmd: >-
    dotnet --info

    c:\mp\.nuget\nuget.exe update -self
    
    c:\mp\.nuget\nuget.exe restore

    cov-build.exe --dir cov-int msbuild.exe MissionPlanner.sln /m /l:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    7z a -tzip MissionPlannerCov-int.zip c:\mp\bin\Release\net461\* 

test: off
artifacts:
- path: MissionPlannerCov-int.zip
  name: MissionPlannerCov-int
- path: MissionPlannerBeta.zip
  name: MissionPlannerBeta
- path: checksums.txt
  name: checksums
deploy: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/c7f1e74edef028cfa905
  method: POST
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
